version: "3.8"

services:
  postgres:
    image: postgres:17.0-alpine3.19
    container_name: local-postgres
    restart: always
    environment:
      POSTGRES_DB: db_test
      POSTGRES_USER: pius
      POSTGRES_PASSWORD: piuspius
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network

volumes:
  postgres_data:
    driver: local

networks:
  backend_network:
    driver: bridge
